services:
  mongo:
    image: mongo:7
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "3000:3000"
    depends_on:
      - user-service
      - jobprep-service
      - interview-session-service
    environment:
      - PORT=3000
      - USER_SERVICE=http://user-service:8080
      - JOBPREP_SERVICE=http://jobprep-service:8081
      - SESSION_SERVICE=http://interview-session-service:8082
      - JWT_SECRET=key

  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "8080:8080"
    depends_on:
      - mongo
      - redis
    environment:
      - MONGO_URI=mongodb://mongo:27017/userdb
      - JWT_SECRET=key
      - REDIS_URL=redis://redis:6379

  jobprep-service:
    build: ./jobPrep-service
    container_name: jobprep-service
    ports:
      - "8081:8081"
    depends_on:
      - mongo
      - redis
    environment:
      - MONGO_URI=mongodb://mongo:27017/jobprep
      - JWT_SECRET=key
      - GEMINI_API_KEY=Your_Api_key
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./jobPrep-service:/app
      - /app/node_modules

  interview-session-service:
    build: ./interview-session-service
    container_name: interview-session-service
    ports:
      - "8082:8082"
    depends_on:
      - mongo
      - redis
    environment:
      - PORT=8082
      - MONGO_URI=mongodb://mongo:27017/interview-session-service
      - JWT_SECRET=key
      - GEMINI_API_KEY=Your_Api_key
      - JOBPREP_SERVICE_URL=http://jobprep-service:8081/api/v1/interview
      - REDIS_URL=redis://redis:6379

volumes:
  mongo_data:
