services:
  mongo:
    image: mongo:7
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "${PORT_API_GATEWAY}:3000"
    depends_on:
      - user-service
      - jobprep-service
      - interview-session-service
      - redis
    environment:
      - PORT=${PORT_API_GATEWAY}
      - USER_SERVICE=http://user-service:8080
      - JOBPREP_SERVICE=http://jobprep-service:8081
      - SESSION_SERVICE=http://interview-session-service:8082
      - JWT_SECRET=${JWT_SECRET}
      - REDIS_URL=${REDIS_URL}
      - REDIS_JWT_TTL=${REDIS_JWT_TTL}

  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      - PORT=${PORT_USER}
      - MONGO_URI=${MONGO_URI_USER}
      - JWT_SECRET=${JWT_SECRET}

  jobprep-service:
    build: ./jobPrep-service
    container_name: jobprep-service
    ports:
      - "8081:8081"
    depends_on:
      - mongo
    environment:
      - PORT=${PORT_JOB}
      - MONGO_URI=${MONGO_URI_JOB_PREP}
      - GEMINI_API_KEY=${GEMINI_API_KEY_JOB_PREP}
    volumes:
      - ./jobPrep-service:/app
      - /app/node_modules

  interview-session-service:
    build: ./interview-session-service
    container_name: interview-session-service
    ports:
      - "8082:8082"
    depends_on:
      - mongo
    environment:
      - PORT=${PORT_SESSION}
      - MONGO_URI=${MONGO_URI_SESSION}
      - GEMINI_API_KEY=${GEMINI_API_KEY_SESSION}
      - JOBPREP_SERVICE_URL=${JOBPREP_SERVICE_URL}

volumes:
  mongo_data:
